# Generated by Django 5.1.2 on 2024-10-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='borrower',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.borrower'),
        ),
    ]
