# Generated by Django 5.1.2 on 2024-10-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together={('member', 'item', 'date')},
        ),
    ]
