# Generated by Django 5.1.2 on 2024-10-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_item_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='loandate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
