# Generated by Django 5.1.2 on 2024-10-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_item_loandate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.borrower'),
        ),
    ]
