# Generated by Django 5.1.2 on 2024-10-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_item_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
